# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    tags: 
      - '*'
    # branches: [ main ]
  # pull_request:
    # branches: [ main ]

jobs:
  build-windows:

    runs-on: [ windows-latest ]

    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
    - name: Checkout code
      uses: actions/checkout@main
    - name: Extract version
      id: extract_version
      uses: Saionaro/extract-package-version@v1.0.6
    - name: Print version
      run: echo ${{ steps.extract_version.outputs.version }}
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.extract_version.outputs.version }}
        tag_name: ${{ github.ref }}
        body_path: 'Release ${{steps.extract_version.outputs.version}}'
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    # - run: npm test
    - run: npm run make --if-present
    - uses: actions/upload-artifact@v2
      with:
        name: s3client-win32-x64
        path: packages/s3client-win32-x64.zip
    - uses: actions/upload-artifact@v2
      with:
        name: s3client-win32-ia32
        path: packages/s3client-win32-ia32.zip
    - uses: actions/upload-artifact@v2
      with:
        name: s3client-win32-arm64
        path: packages/s3client-win32-arm64.zip
    - uses: actions/upload-artifact@v2
      with:
        name: s3client-win32-installer
        path: packages/s3client-${{steps.extract_version.outputs.version}}-setup.exe
    - name: upload linux artifacts
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: packages/s3client-win32-x64.zip
        asset_name: s3client-win32-x64
        asset_content_type: application/zip
  build-linux:

    runs-on: [ ubuntu-latest ]

    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    # - run: npm test
    - run: npm run make --if-present
    - uses: actions/upload-artifact@v2
      with:
        name: s3client-linux-x64
        path: packages/s3client-linux-x64.zip
    - uses: actions/upload-artifact@v2
      with:
        name: s3client-linux-armv7l
        path: packages/s3client-linux-armv7l.zip        
    - uses: actions/upload-artifact@v2
      with:
        name: s3client-linux-ia32
        path: packages/s3client-linux-ia32.zip        
    - uses: actions/upload-artifact@v2
      with:
        name: s3client-linux-arm64
        path: packages/s3client-linux-arm64.zip
    - uses: actions/upload-artifact@v2
      with:
        name: s3client-linux-installer
        path: packages/s3client-linux-x64.deb

  build-darwin:

    runs-on: [ macos-latest ]

    strategy:
      matrix:
        node-version: [ 12.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i -g npm
    - run: npm ci
    # - run: npm test
    - run: npm run make --if-present
    - uses: actions/upload-artifact@v2
      with:
        name: s3client-darwin-x64
        path: packages/s3client-darwin-x64.zip
    - uses: actions/upload-artifact@v2
      with:
        name: s3client-darwin-arm64
        path: packages/s3client-darwin-arm64.zip        